project_id = "pmlsgbqlexwffqxvsuaj"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.shopify-orders]
verify_jwt = true

[functions.shopify-sync]
verify_jwt = true

[functions.shopify-orders-webhook]
verify_jwt = false
